### ISSUE TITLE
token authentication

### ISSUE THREAD

**Issue by nopctoday** [jonashagstedt/swampdragon-auth#10]
Hi Jonas, I am trying to complete your implementation of Token authentication. However, I am having a bit difficulty finding the exact purpose of TokenAuthMixin . I understand it needs to be called during 'subscribe' so that user obj can be retrieved via token, but I am not sure where it needs to be triggered.

**Comment by nopctoday** [comment]
My mistake, TokenAuthMixin is meant to be placed in the router inheritance. I was stupid. Now i've figured it out. thanks again jonas for all your hard work!!!

**Comment by jonashagstedt** [comment]
No problem, happy it worked out!
