### ISSUE TITLE
Not able to create user specific channels

### ISSUE THREAD

**Issue by himanshunimje** [jonashagstedt/swampdragon-auth#11]
Hey,

I have been trying to implement user specific real time notifications in a project. While I was able to broadcast the real time notifications, I am facing a stiff struggle to create user specific channels, where selected notifications are sent to user. As far as my attempt for the same goes, following are the pieces of code that I have written after looking at a few examples using swampdragon-auth:

routers.py:

    class NotificationRouter(ModelPubRouter):
        valid_verbs = ['subscribe']
        route_name = 'notifications'
        model = Notification
        serializer_class = NotificationSerializer

        def get_query_set(self, **kwargs):
            return self.model.objects.filter(user=self.connection.user)

        def get_object(self, **kwargs):
            return self.model.objects.get(user=self.connection.user, pk=kwargs['pk'])

        def get_subscription_contexts(self, **kwargs):
            return {'user__id': self.connection.user.pk}

models.py

    class Notification(SelfPublishModel, models.Model):
        serializer_class = NotificationSerializer
        message = models.TextField()
        verb = models.CharField(null=True, default="achieved", max_length=20)
        user = models.ForeignKey(settings.AUTH_USER_MODEL)

and serializer.py

    class NotificationSerializer(ModelSerializer):
        class Meta:
            model = 'notifications.Notification'
            publish_fields = ['message','verb','user']

This code does not achieves the user specific notifications execution and broadcasts messages to all users. As far I believe, get_subscription_contexts is the function which filters the notifications to selected users, but I am not able to achieve that with this code. It would be great if anyone could help me resolve this issue.

Thanks 
Himanshu

**Comment by jonashagstedt** [comment]
Put a breakpoint in `get_subscription_contexts` and make sure that it's called.

You should probably override `subscribe` as well and make sure you have a user, or implement a permission.

**Comment by himanshunimje** [comment]
Thanks for your reply.

The function 'get_subscription_contexts' is getting called as I used used ipdb as you have mentioned here (https://github.com/jonashagstedt/swampdragon-auth/issues/8). The ipdb trace confirmed that that the self.connection.user did pass the user object.

Just to clarify about the second statement, should I add 'user' as a parameter to the subscribe function described in swampdragon.js:
swampdragon.subscribe = function(route, channel, args, success, failure) {
    return swampdragon.callRouter('subscribe', route, args, success, failure, channel);
};

Thanks for your help.

**Comment by jonashagstedt** [comment]
You don't need to add the user.

After you've subscribed, run `redis-cli` to connect to your redis server and run `PUBSUB CHANNELS` to see if there is a channel that exists with the user pk as specified.

There is a project for notifications going already: 
https://github.com/jonashagstedt/swampdragon-notifications

You can look at how things are done there as it filters by users (also keeps track of online users etc.)

**Comment by hagsteel** [comment]
Closing this issue for now. If you are still stuck feel free to keep commenting
