### ISSUE TITLE
get_user returns None

### ISSUE THREAD

**Issue by vahid0000** [jonashagstedt/swampdragon-auth#14]
Hello
We have a problem in getting user from self.connection.user, which it does not return user object And the output of "PUBSUB channels" in redis-cli is "(empty list or set)"
Our router code is:
```
from swampdragon.route_handler import ModelPubRouter
from swampdragon import route_handler
from common.customerdeal.models import CustomerDeal
from common.customerdeal.serializers import CustomerDealSerializer

class CustomerDealRouter(ModelPubRouter):
    route_name = 'deal-route'
    serializer_class = CustomerDealSerializer
    model = CustomerDeal

    def updated(self, obj, **kwargs):
        return

    def deleted(self, obj, obj_id, **kwargs):
        return


    def get_object(self, **kwargs):
        return self.model.objects.get(customer__user=self.connection.user)
    #
    def get_query_set(self, **kwargs):
        return self.model.objects.filter(customer__user = self.connection.user)

    def get_subscription_contexts(self, **kwargs):
        return {'customer__user__pk': self.connection.user.pk}

route_handler.register(CustomerDealRouter)
```
---------------------------------------------------------- ERROR --------------------------------------------------
```
ERROR:tornado.general:WebSocket
Traceback (most recent call last):
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/sockjs/tornado/transports/websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 90, in on_message
    raise e
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 87, in on_message
    handler(self).handle(data)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/route_handler.py", line 65, in handle
    m(**kwargs)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/route_handler.py", line 255, in subscribe
    server_channels = make_channels(self.serializer_class, self.include_related, self.get_subscription_contexts(**kwargs))
  File "/Users/vahid/virtualenvs/goldir/goldir/common/customerdeal/routers.py", line 25, in get_subscription_contexts
    return {'customer__user__pk': self.connection.user.pk}
AttributeError: 'NoneType' object has no attribute 'pk'
ERROR:tornado.application:Uncaught exception in /data/300/jzyvqyaf/websocket
Traceback (most recent call last):
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/sockjs/tornado/transports/websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 90, in on_message
    raise e
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 87, in on_message
    handler(self).handle(data)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/route_handler.py", line 65, in handle
    m(**kwargs)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/swampdragon/route_handler.py", line 255, in subscribe
    server_channels = make_channels(self.serializer_class, self.include_related, self.get_subscription_contexts(**kwargs))
  File "/Users/vahid/virtualenvs/goldir/goldir/common/customerdeal/routers.py", line 25, in get_subscription_contexts
    return {'customer__user__pk': self.connection.user.pk}
AttributeError: 'NoneType' object has no attribute 'pk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/tornado/websocket.py", line 402, in _run_callback
    callback(*args, **kwargs)
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/sockjs/tornado/transports/websocket.py", line 70, in on_message
    self.abort_connection()
  File "/Users/vahid/virtualenvs/goldir/lib/python3.4/site-packages/sockjs/tornado/websocket.py", line 28, in abort_connection
    self.ws_connection._abort()
AttributeError: 'NoneType' object has no attribute '_abort'
```

**Comment by jonashagstedt** [comment]
1. Which connection class have you specified in settings
2.  Have you signed in first (e.g go to django admin and sign in)

**Comment by vhdmsm** [comment]
Thank you for your time
This is our connection class in settings:
```
SWAMP_DRAGON_CONNECTION = ('swampdragon_auth.socketconnection.HttpDataConnection', '/data')
```
and yes we're signed in first.

**Comment by vhdmsm** [comment]
After a little work on this, i found that what's the problem and i hope that i'm not wrong. The session key that i printed in the view using "request" is not the same as the session key which is set in the websocket with the following values:
```
JSESSIONID=dummy
sdso=8d559ef1750c47e29fd93a40cc737bf2
```
while my request session key is:
ymoask2hno7l8a3riq2go2n0e35rk6qp

This is why i'm getting None because django get_user() function returns no user with this session key in the session store but if i change the following with my own session key, i can get the user:
```             
user=get_user(_RequestWrapper(self.SessionStore('ymoask2hno7l8a3riq2go2n0e35rk6qp')))
```

**Comment by jonashagstedt** [comment]
Have you set the cookie domain correctly as well?

What  version of Django are you using?
Can you provide as much information as possible so I can replicate this.

**Comment by vhdmsm** [comment]
In local we've no subdomain but in the server swampdragon is running on a subdomain real.example.com and we've set cookie domain in the settings but in both cases it didn't work.
I'm using django 1.6.7 and your last version of 'socketconnection.py' source code in the git because the currently version on pip wasn't compatible with django 1.6.7 and needed to change import_string function to import_by_path.

**Comment by jonashagstedt** [comment]
If you put a breakpoint here:
https://github.com/jonashagstedt/swampdragon-auth/blob/master/swampdragon_auth/socketconnection.py#L28

in your code, does the morsel have a value?

(Also: the session id of the connection is a websocket session, and has nothing to do with the request session.)

**Comment by vahid0000** [comment]
this is self.session.conn_info.cookies and morsel is None
```
JSESSIONID=dummy
sdso=8d559ef1750c47e29fd93a40cc737bf2
```
there is no 'sessionid' in self.session.conn_info.cookies

**Comment by jonashagstedt** [comment]
Does it work if you upgrade to Django 1.7 (for testig purposes).

**Comment by vahid0000** [comment]
I tested Django 1.7 and 1.8 before. However, it doesn't work

**Comment by jonashagstedt** [comment]
Could you create a new project and try to replicate this issue there, and put it on Github so I can see it as well.

Also your cookie domain settings for dev should not be set so if you have that in your local dev settings remove that.

**Comment by vhdmsm** [comment]
Finally one of our best students figured out that what's the problem. we were setting dragon url to:
```
DRAGON_URL = 'http://localhost:9999'
```
but in localhost our server was running on 127.0.0.1 and this is why the cookie is setting on wrong domain. now i set the dragon url to:
```
DRAGON_URL = 'http://127.0.0.1:9999'
```
and it's working like a charm.
Thank you.

**Comment by jonashagstedt** [comment]
That's an interesting one!
If this solves the issue for others please let me know and I'll close this issue knowing the solution (not really something we can fix since this has to do with how browsers handles cookies)

**Comment by vhdmsm** [comment]
Yes it's depend on browser and how they handle cookies. I'll try this on our server domain and i'll report results here as soon as possible.

**Comment by jonashagstedt** [comment]
Grand! thank you

**Comment by hagsteel** [comment]
Closing this issue for now. Feel free to comment on it if there are more things to add.

**Comment by chogarcia** [comment]
thanks for this!

**Comment by PhilippeTrounev** [comment]
Hi,
 I am having trouble getting this to work in production.
In localhost it works fine because I can set

DRAGON_URL = '152.25.32.123:9000'
SWAMP_DRAGON_HOST = ''152.25.32.123'
SWAMP_DRAGON_PORT = '9000'

However in production I set

DRAGON_URL = 'sd.mydomain.com'
SWAMP_DRAGON_HOST = '127.0.0.1' or SWAMP_DRAGON_HOST = 'myinternalP' 
SWAMP_DRAGON_PORT = '9000'
SESSION_COOKIE_DOMAIN = ".mydomain.com

SD works with either configuration. The domains resolve and swampdragon.js config is available,

but sessionid and csrf token are not passed with the session therefore user keeps returning None.

Any suggestions are appreciated...
