### ISSUE TITLE
Correctly Handle Session Resolution

### ISSUE THREAD

**Issue by cancan101** [jonashagstedt/swampdragon-auth#2]
Compare [this code in swampdragon-auth](https://github.com/jonashagstedt/swampdragon-auth/blob/4001a46a2b60e2320072c1c1d3b89e33529485bd/swampdragon_auth/socketconnection.py#L18) to the same [Django code](https://github.com/django/django/blob/731f313d604a6cc141f36d8a1ba9a75790c70154/django/contrib/sessions/backends/db.py#L19). The Django code checks cookie expiration. 

Further you should not assume that the user is using a db session. Rather you want to use a level of indirection and go to the `SessionStore`: https://github.com/django/django/blob/731f313d604a6cc141f36d8a1ba9a75790c70154/django/contrib/sessions/middleware.py#L16

See: https://docs.djangoproject.com/en/1.7/topics/http/sessions/

**Comment by jonashagstedt** [comment]
A very valid point. I'll look into it

**Comment by jonashagstedt** [comment]
I rewrote the entire `get_user` function. 
Good spot.
