### ISSUE TITLE
Session.get_decoded hash check sometimes fails

### ISSUE THREAD

**Issue by maxdore** [jonashagstedt/swampdragon-auth#3]
The decoding of sessions sometimes fails in Django, caused by a failing hash check. See this post for reference: http://stackoverflow.com/questions/13146794/how-to-overcome-session-get-decoded-hash-check

I dont know why this happens or if it will get solved in Django, but Swampdragon-Auth should reflect this failure.

I have solved this problem by decrypting the session manually, would you accept a PR?

**Comment by jonashagstedt** [comment]
Absolutely. 
Make a PR and I'll check it and merge it.
This package does need some TLC so pull requests are more than welcome
