### ISSUE TITLE
session lookup won't work with user_sessions

### ISSUE THREAD

**Issue by griphiam** [jonashagstedt/swampdragon-auth#7]
user_sessions (http://django-user-sessions.readthedocs.org/en/latest/reference.html) is an improved db session management, which unfortunately breaks the __init__ assumption that is made in the HttpDataConnection module (requires an IP and user-agent strings).

Not sure if there is a more generic way of looking up the session from the DB without constructing a new session engine.  In the worst case, there would be a second HttpDataConnection class that supports the user_sessions engine.

Not sure if you want to support this out of the box or have it be left to the user an an exercise.  For now, I'll probably write my own class to get around this.  Let me know if you want me to contribute it back.

**Comment by jonashagstedt** [comment]
Can you see a way of providing this without breaking the existing implementation?

If you don't, and you end up writing your own, feel free to send me a link and I'll post it on [http://swampdragon.net](http://swampdragon.net/packages/)  (if you are okay with that).

**Comment by hagsteel** [comment]
Closing this for now. Feel free to reopen if you want to add something
