### ISSUE TITLE
AttributeError: 'Router' object has no attribute 'user' problem

### ISSUE THREAD

**Issue by ramapat** [jonashagstedt/swampdragon-auth#8]
Hello, 

I'm not an experienced developer and i'm having some difficulties with implementing swampdragon-auth into my project.I followed this tutorial http://wildfish.com/blog/2014/12/09/swampdragon-real-time-django-notifications/ and everything works fine. Then i make the changes in the "Additional Notes" part. 
Also i added
"swampdragon_auth" in INSTALLED_APPS 
and 
SWAMP_DRAGON_CONNECTION = ('swampdragon_auth.socketconnection.HttpDataConnection', '/data') into settings file.

When i open the notification URL swampdragon server throws this exception:

Running SwampDragon on 127.0.0.1:9999
ERROR:tornado.general:WebSocket
Traceback (most recent call last):
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/sockjs/tornado/transports/websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 79, in on_message
    raise e
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 76, in on_message
    handler(self).handle(data)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/swampdragon/route_handler.py", line 62, in handle
    m(**kwargs)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
AttributeError: 'NotificationRouter' object has no attribute 'user'
ERROR:tornado.application:Uncaught exception in /data/752/l5won5g4/websocket
Traceback (most recent call last):
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/sockjs/tornado/transports/websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 79, in on_message
    raise e
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/swampdragon/connections/sockjs_connection.py", line 76, in on_message
    handler(self).handle(data)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/swampdragon/route_handler.py", line 62, in handle
    m(**kwargs)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
AttributeError: 'NotificationRouter' object has no attribute 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/tornado/websocket.py", line 402, in _run_callback
    callback(*args, **kwargs)
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/sockjs/tornado/transports/websocket.py", line 70, in on_message
    self.abort_connection()
  File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site-packages/sockjs/tornado/websocket.py", line 28, in abort_connection
    self.ws_connection._abort()
AttributeError: 'NoneType' object has no attribute '_abort'

I'm stuck and i don't know what to do. Any help would be highly appreciated.

**Comment by jonashagstedt** [comment]
It looks like you are trying to access the user directly via the router.

Access the user via the connection instead: `self.connection.user` (rather than `self.user`)

**Comment by ramapat** [comment]
This method is the only place that I access the user 

def get_subscription_contexts(self, **kwargs):
    return {'user_id': self.connection.user.pk}

Other than that anything comes into your mind?

**Comment by jonashagstedt** [comment]
Could you share your router?
Including import statement? 

This part here:

>File "/Users/ramapat/Desktop/workspace/Env/lib/python3.4/site->packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
>if test_func(request.user):

Looks a bit dodgy to me

**Comment by ramapat** [comment]
from swampdragon import route_handler
from swampdragon.route_handler import ModelPubRouter
from .models import Notification
from .serializers import NotificationSerializer
from django.contrib.auth.decorators import login_required


class NotificationRouter(ModelPubRouter):
    valid_verbs = ['subscribe']
    route_name = 'notifications'
    model = Notification
    serializer_class = NotificationSerializer

    @login_required
    def subscribe(self, **kwargs):
        super().subscribe(**kwargs)

    def get_subscription_contexts(self, **kwargs):
        return {'user_id': self.connection.user.pk}

route_handler.register(NotificationRouter)

**Comment by jonashagstedt** [comment]
Here is your problem:

`from django.contrib.auth.decorators import login_required`

and

`@login_required`

These are Django view specifics. 

See this: http://swampdragon.net/documentation/permissions/

**Comment by ramapat** [comment]
Okay i read it but i'm already using swampdragon-auth. I deleted the the login_required decorator but still self. connection.user returns similar exception. 

return {'user_id': self.connection.user.pk}
AttributeError: 'NoneType' object has no attribute 'pk'

if you are still interested here is the code:
https://github.com/ramapat/swamp

**Comment by jonashagstedt** [comment]
`self.connection.user` will be none if the user is not signed in.

Are you doing all this on local host as well?

**Comment by ramapat** [comment]
Yes i'm on local host. Before loading the page, I am signed in to the admin page and print self.request.user to the console in the view class to verify it.

**Comment by jonashagstedt** [comment]
Works fine for me:

    
    ipdb> l
         14     #def subscribe(self, **kwargs):
         15     #    super().subscribe(**kwargs)
         16 
         17     def get_subscription_contexts(self, **kwargs):
         18         import ipdb;ipdb.set_trace()
    ---> 19         return {'user_id': self.connection.user.pk}
         20 
         21 route_handler.register(NotificationRouter)
    
    ipdb> self.connection.user
    <User: jonas>
    ipdb>

**Comment by jonashagstedt** [comment]
run `pip install ipdb` and add line 18 and you can check the user.

**Comment by ramapat** [comment]
18         import ipdb;ipdb.set_trace()
---> 19         return {'user_id': self.connection.user}
     20

ipdb> self.connection.user
ipdb>

It returns nothing :/

**Comment by jonashagstedt** [comment]
The exact steps:

1.  http://localhost:8000/admin/
2.  sign in
3.  http://localhost:8000/
4.  this hits the breakpoint
5.  `self.connection.user` now returns the admin user

**Comment by jonashagstedt** [comment]
You have two swampdragon declared in your requirements.txt
1.  Delete the one with the specific version number
2.  pip install -r requirements.txt --upgrade

**Comment by ramapat** [comment]
1. Deleted the one with the specific version number
2. Deleted the one with the specific version number from the requirements.txt
3. pip install -r requirements.txt --upgrade

and this is the output of pip freeze:
Django==1.7
SwampDragon==0.4.1.2
SwampDragon-auth==0.1.3
Whoosh==2.6.0
certifi==14.05.14
django-haystack==2.3.1
gnureadline==6.3.3
ipdb==0.8
ipython==3.0.0
python-dateutil==2.4.1
redis==2.10.3
six==1.9.0
sockjs-tornado==1.0.1
tornado==4.1
tornado-redis==2.4.18
urllib3==1.10.2

1. http://localhost:8000/admin/
2. sign in
3. http://localhost:8000/
4. this hits the breakpoint
5. self.connection.user now returns the admin user

I did exactly what you say but results are the same.
Sorry, I'm starting to feel bad about stealing your time. We can stop here if you want

**Comment by jonashagstedt** [comment]
Nonsense! We'll fix this.

One thing: do you have redis 2.8 and is it running?

**Comment by ramapat** [comment]
Yes it's running and 2.8.19

**Comment by jonashagstedt** [comment]
Okay let's replicate exactly what I did:

1.  `mkvirtualenv swamp`
2.  `git clone https://github.com/ramapat/swamp`
3.  Remove duplicate SwampDragon from requirements (use the one without version info)
4.  `pip install -r requirements.txt`
5.  `pip install ipdb`
6.  `./manage.py createsuperuser` (make a new one)
7.  edit routers.py and add `import ipdb;ipdb.set_trace()` in `get_subscription_contexts`
8.  `./manage.py runsd`
9.  open a new terminal and `./manage.py runserver`
10.  browse to http://localhost:8000/admin/ and log in
11.  browse to http://localhost:8000

**Comment by ramapat** [comment]
This is crazy. I created a new project. My redis server is running.. however, no luck.

Only thing i made it different is creating a virtual environment with "virtualenv -p python3" command like i always do. mkvirtualenv command is not working.

**Comment by jonashagstedt** [comment]
Py3 should not be an issue but try it with py2

**Comment by ramapat** [comment]
I tried with py2 but nothing is changed.

Oh i may forgot to mention about something really important :( I think pip installation of swampdragon-auth is an older version(socketconnection.py is different from current one). But when i try what we did for the first time I use the new version(installed with pip from git repository and i didn't update the requirements.txt ) but when i created a new project for the second time I run the pip install -r requirements.txt command. Now we both have the same(older) version i guess..

**Comment by jonashagstedt** [comment]
okay let's try again:

Follow every point:

*  `cd`
*  `mkdir tryagain`
*  `cd tryagain`
*  `git clone git@github.com:ramapat/swamp.git`
*  `cd swamp`
*  `virtualenv -p python3 /tmp/swamp`
*  `source /tmp/swamp/bin/activate`
*  `rm requirements.txt`
*  `echo swampdragon >> requirements.txt`
*  `echo swampdragon-auth >> requirements.txt`
*  `echo ipdb >> requirements.txt`
*  `pip install -r requirements.txt`
*  `vim demo/routers.py` and add `import ipdb;ipdb.set_trace()` (like before)
*  `./manage.py createsuperuser`
*  `./manage.py runserver`
*  open another terminal window
*  `source /tmp/swamp/bin/activate`
*  `./manage.py runsd`
*  open browser to http://localhost:8000/admin/
*  browse to http://localhost:8000/
*  In the terminal that is now stuck on the breakpoint: `print(self.connection.user.pk)` 

get subscription should look like this now

    def get_subscription_contexts(self, **kwargs):
        import ipdb;ipdb.set_trace()
        return {'user_id': self.connection.user.pk}

**Comment by ramapat** [comment]
I swear copy and pasted every single line.

ipdb> print(self.connection.user.pk)
*** AttributeError: 'NoneType' object has no attribute 'pk'

**Comment by jonashagstedt** [comment]
Okay try clearing out your pyc and __pycache__

**Comment by ramapat** [comment]
I have just deleted all the *.pyc files.

aaand same results :)

**Comment by jonashagstedt** [comment]
Okay this is mind boggling. Do you have another mac laying around you can try this on?

**Comment by ramapat** [comment]
Just a windows 8 computer but i can try this on some cloud hosting website? probably on ubuntu

**Comment by jonashagstedt** [comment]
Windows will probably cause you more grief than anything.

You could probably run a virtualbox with Ubuntu.
This is mindboggling though.

One more thing we could try:
Without activating any virtualenvs: pip uninstall swampdragon swampdragon-auth  (and more things that might be installed in your public site packages).

It could be the case that something old and deprecated is in use

**Comment by ramapat** [comment]
I tried on a ubuntu machine and still having the same problem but I think i found the root cause of the problem. 

sockjs.tornado.ConnectionInfo object doesn't have a cookie named sessionid or can not access idk. 
morsel = self.session.conn_info.cookies.get(cookie_name)
session = self.SessionStore(morsel.value)

i copy pasted the sessionid after ipdb stops 
ipdb>django.contrib.auth.get_user(_RequestWrapper(self.SessionStore('ubb1d70rnnzzngvmucclzx6mclag23h1'))) 
<User: osboxes>

and it works fine.
I'm curious about how is your machine access the cookie :)

**Comment by jonashagstedt** [comment]
That's odd. I have no issues on either OSX or Ubuntu and I've not heard anyone else having issues either.

Have you tried starting a project from scratch that only grabs the logged in user?

**Comment by ramapat** [comment]
Sorry, I don't really understand what you want me to do

**Comment by vhdmsm** [comment]
i have exactly the same problem, this is really annoying :( can anyone suggest any solution?

**Comment by sruon** [comment]
Facing the same issue. Using a breakpoint I get this in the cookie store

ipdb> print self.connection.session.conn_info.cookies
Set-Cookie: csrftoken=V6ILGGTWJQai87dg1I5lWyKMZOSIuaHb
Set-Cookie: sdso=9233e42fdb6e4c56a04b9886be67b243
ipdb>

Notice how the sessionid Cookie is missing, which is the central part of the swampdragon-auth code. I have cross referenced it with Google Chrome and I see this corresponds to the websocket request made to the server, which indeed is missing a sessionid.

Not sure how to fix this at this point.

**Comment by jonashagstedt** [comment]
I'm reopening this.

Could someone who has this problem share a project with me on Github so I can replicate this (don't need to share the actual project, just make a very basic one that experience this problem).
along with what python version you are using (include a requirements file too).

If this can be done then I can try to fix it straight away.

**Comment by sruon** [comment]
@jonashagstedt this is actually fixed by this fix https://github.com/jonashagstedt/swampdragon-auth/issues/14#issuecomment-105885429

Thanks everyone involved, we should document it.

**Comment by jonashagstedt** [comment]
Good stuff!
I'll close this for now
